# Site settings
title: ICFP Contest Archive
email: your-email@domain.com
description: >
  An unofficial archive of task descriptions and supporting files for past
  ICFP Programming Contests.
url: "http://icfpcontest.github.io"
permalink: "/:categories/:year/:title.html"

#twitter_username: jekyllrb
github_username:  icfpcontest

# Build settings
markdown: kramdown

exclude: [vendor, Gemfile, Gemfile.lock]
